dist: xenial
language: python
matrix:
  include:
  - name: Python 3.7.1 on Xenial Linux
    python: 3.7
    dist: xenial
  - name: Python 3.7.6 on macOS sierra
    os: osx
    osx_image: xcode9.2
    language: shell
    before_install:
    - unset PYENV_ROOT
    - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - export PATH="$HOME/.pyenv/bin:$PATH"
    - env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.7.6
    - pyenv global system 3.7.6
    - eval "$(pyenv init -)"
    - echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  - name: Python 3.7.6 on Windows
    os: windows
    language: shell
    before_install:
    - choco install zip & choco install python --version 3.7.6
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH 
install:
- pip3 install coverage
- pip3 install -r pysper/requirements.txt
script:
- scripts/cov
- scripts/lint
- scripts/build
